name: fvdb_maskpls
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pytorch-gpu=2.8.0[build=cuda129*]
  - pip
  - git
  - gitpython
  - ipython
  - tqdm
  - tyro
  - scikit-learn
  - py-opencv
  - imageio
  - pip:
    - pye57
