name: fvdb_garfvdb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - fvdb-core>=0.4.2,<0.5.0
  - cxx-compiler
  - blas=*=mkl
  - python=3.12
  - pytorch-gpu=2.10.0
  - cuda-version>=12.9
  - pip
  - git
  - gitpython
  - ipython
  - tqdm
  - numpy
  - tyro
  - scikit-learn
  - py-opencv
  - open-clip-torch
  - openusd
  - imageio
  - sam2
  - pyproj
  - transformers
  - pycocotools
  - tensorboard
  - boto3
  - requests
  - scikit-image
  - scipy
  - torchvision
  - msgpack-python
  - huggingface_hub
  - rapidsai::cuml
  - cupy
  - matplotlib
  - pip:
    - dlnr_lite
    - fvdb-reality-capture>=0.4.0<0.5.0
    - nanovdb-editor>=0.0.24
